[package]
name = "sdp-xml-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = "0.17.3"
num-traits = "0.2.19"
sdp-xml = { git = "https://github.com/eyanje/sdp-xml", version = "0.1.0" }
uuid = "1.11.0"
xml = "0.8.20"
